### ISSUE TITLE
[새로운기능] 점주 클래스 생성

### ISSUE THREAD

**Issue by Taewoongjung** [f-lab-edu/foody-lab#30]
* 점주를 등록할 수 있다.
* 점주는 가게를 소유할 수 있다.

### 데이터베이스 연결 후 추가할 테스트:
* 점주는 가게를 등록할 수 있다.
* 점주는 가게를 닫을 수도 있고 열 수도 있다.

**Comment by Bue-von-hon** [comment]
이번 이슈에서는 점주와 가게가 등장하겠군요ㄷㄷ
다만 점주와 가게의 어떤 역할을 구현하려는지 짐잣이 안가는데 추가해주시면 좋을것 같습니다..!

> 점주를 등록할 수 있다.

이건 무슨 의미일까요..?

**Comment by Bue-von-hon** [comment]
[d-1] 10월 27일까지🔥🔥

**Comment by Taewoongjung** [comment]
> > 점주를 등록할 수 있다.
> 
> 이건 무슨 의미일까요..?

점주 객체를 만드는 것입니다.

**Comment by Bue-von-hon** [comment]
개발 영역 줄이기 방침에 따라 close
