### ISSUE TITLE
KakaoPayImpl 리팩터링

### ISSUE THREAD

**Issue by Taewoongjung** [f-lab-edu/foody-lab#37]
-        이 부분은 단순히 true/false의 응답 대신에 처리 결과를 더 명확하게 나타내줘도 좋을 것 같아요~
https://developers.kakao.com/docs/latest/ko/kakaopay/single-payment#request
카카오페이 API를 봐도 엄청나게 많은 데이터를 던져주고 있어요. 
요청 id라던지, 금액, 결제 시간과 같은 여러가지 데이터를 주고 있는데요.

이런 데이터를 기반으로 성공/실패를 구분하거나 http status로 성공/실패를 구분해도 좋을 것 같습니다.
true/false로만 표현하기에는 정보가 좀 적은 것 같네요~

_Originally posted by @f-lab-Carrey in https://github.com/f-lab-edu/foody-lab/pull/35#discussion_r1010257828_
      

-         위의 코드를 간결하게 바꾸면.. 아래와 같이 표현할 수도 있지 않나요?
```java
    @Override
    public boolean processPay(long price) {
        return requestPay() && approvePay();
    }
```

_Originally posted by @f-lab-Carrey in https://github.com/f-lab-edu/foody-lab/pull/35#discussion_r1010258559_

**Comment by Taewoongjung** [comment]
[d-2] 11월 3일까지🔥🔥

**Comment by Bue-von-hon** [comment]
[d-1] 11월 4일까지
