### ISSUE TITLE
[bugfix] main에 merge된 브랜치 내용을 dev로 가져오기

### ISSUE THREAD

**Issue by Bue-von-hon** [f-lab-edu/foody-lab#45]
## Description
이전에 merge된 mapstruct 브랜치가 main에 merge되었습니다
원래 dev에 merge가 되었어야 했는데....
이를 바로잡기 위해 브랜치를 생성합니다...😭(미리 확인을 했어야 했어요...)

**Comment by Taewoongjung** [comment]
누구나 실수할 수 있죠!
